plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'org.liquibase.gradle' version '2.1.1'
}

group = 'edu.school21'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    implementation 'org.postgresql:postgresql:42.7.2'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.17.2'
    liquibaseRuntime 'org.liquibase:liquibase-core:4.29.2', 'info.picocli:picocli:4.7.6', 'org.postgresql:postgresql:42.7.4', 'org.yaml:snakeyaml:2.3'
}

apply plugin: "org.liquibase.gradle"

liquibase {
    activities {
        mainActivity {
            changelogFile 'src/main/resources/migrations/db.changelog-master.yaml'
            url 'jdbc:postgresql://localhost:5432/postgres'
            username 'postgres'
            password 'postgres'
            liquibaseSchemaName 'liquibase'
            defaultSchemaName 'app'
        }
    }
    runList = ['mainActivity']
}

jar {
    manifest {
        attributes 'Main-Class': 'edu.school21.info21.Info21Application'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
