version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: authdb
    volumes:
      - mongo_data:/data/db

  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./core/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase
    depends_on:
      - postgres
    environment:
      LIQUIBASE_COMMAND_USERNAME: ${POSTGRES_USER}
      LIQUIBASE_COMMAND_PASSWORD: ${POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: liquibase
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: app
      LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog-master.yaml
    volumes:
      - ./core/src/main/resources/migrations:/liquibase/changelog
    command:
      - update

volumes:
  postgres_data:
  mongo_data:
